### PR TITLE
Type styling fixes

### LINKED ISSUE #51: title off center on android when back button present
https://github.com/aksonov/react-native-router-flux/issues/2467

### PR DESCRIPTION
**Pull request by mikeyrayvon**
close #51

### CODE REVIEW

File: src/native/components/lotes/LotesListItemObra.js [hunk 1]
```diff
@@ -11,8 +11,8 @@ const LotesListItemObra = ({
 
   return (
     <View style={styles.paddingBottomSmall}>
-      <Text><Text style={styles.fontItalic}>{obra.title}</Text>, {obra.year}</Text>
-      <Text>{obra.materials}</Text>
+      <Text style={[{color: 'black'}]}><Text style={[styles.fontItalic, {color: 'black'}]}>{obra.title}</Text>, {obra.year}</Text>
```
Comment (varffs) [inline src/native/components/lotes/LotesListItemObra.js:14]: how come this doesn't use the global black?

**Review by varffs — COMMENTED** [review]
Question about globals.

And the gap between the filters and the cancel button feels kinda weird. Not impossible but not sure if desired/happens on droid.

file 27-02-2018 16 16 19
